# Generated by Django 4.2.30 on 2026-05-27 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название бренда')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Бренд запчастей',
                'verbose_name_plural': 'Бренды запчастей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('name', models.CharField(max_length=100, verbose_name='Название модели')),
                ('generation', models.CharField(blank=True, max_length=100, verbose_name='Поколение или годы выпуска')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул/OEM')),
                ('name', models.CharField(max_length=255, verbose_name='Название детали')),
                ('category', models.CharField(choices=[('suspension', 'Подвеска'), ('brakes', 'Тормозная система'), ('engine', 'Двигатель'), ('filters', 'Фильтры'), ('belts', 'Ремни и шкивы'), ('rubber', 'Резинотехника'), ('other', 'Прочее')], max_length=30, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('price_old', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена')),
                ('in_stock', models.IntegerField(default=0, verbose_name='Наличие на складе')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Вес (кг)')),
                ('hs_code', models.CharField(blank=True, max_length=20, verbose_name='HS код')),
                ('image', models.ImageField(blank=True, null=True, upload_to='parts/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('applicable_cars', models.ManyToManyField(related_name='parts', to='catalog.carmodel', verbose_name='Применимые модели автомобилей')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='catalog.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
                'ordering': ['sku'],
            },
        ),
    ]
