# Generated by Django 4.2.30 on 2026-05-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_part_options_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['sku'], 'verbose_name': 'Запчасть', 'verbose_name_plural': 'Запчасти'},
        ),
        migrations.AlterField(
            model_name='order',
            name='client_phone',
            field=models.CharField(max_length=20, verbose_name='Телефон клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('done', 'Выполнен')], default='new', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления заказа'),
        ),
    ]
